/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoutineRouteImport } from './routes/routine'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AppearanceRouteImport } from './routes/appearance'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionNewRouteImport } from './routes/session.new'
import { Route as SessionIdRouteImport } from './routes/session.$id'
import { Route as ProfileSetupRouteImport } from './routes/profile.setup'
import { Route as SessionIdSummaryRouteImport } from './routes/session.$id.summary'
import { Route as SessionIdReflectRouteImport } from './routes/session.$id.reflect'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutineRoute = RoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AppearanceRoute = AppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionNewRoute = SessionNewRouteImport.update({
  id: '/session/new',
  path: '/session/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile/setup',
  path: '/profile/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIdSummaryRoute = SessionIdSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => SessionIdRoute,
} as any)
const SessionIdReflectRoute = SessionIdReflectRouteImport.update({
  id: '/reflect',
  path: '/reflect',
  getParentRoute: () => SessionIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/appearance': typeof AppearanceRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/reminders': typeof RemindersRoute
  '/routine': typeof RoutineRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/profile/setup': typeof ProfileSetupRoute
  '/session/$id': typeof SessionIdRouteWithChildren
  '/session/new': typeof SessionNewRoute
  '/session/$id/reflect': typeof SessionIdReflectRoute
  '/session/$id/summary': typeof SessionIdSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/appearance': typeof AppearanceRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/reminders': typeof RemindersRoute
  '/routine': typeof RoutineRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/profile/setup': typeof ProfileSetupRoute
  '/session/$id': typeof SessionIdRouteWithChildren
  '/session/new': typeof SessionNewRoute
  '/session/$id/reflect': typeof SessionIdReflectRoute
  '/session/$id/summary': typeof SessionIdSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/appearance': typeof AppearanceRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/reminders': typeof RemindersRoute
  '/routine': typeof RoutineRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/profile/setup': typeof ProfileSetupRoute
  '/session/$id': typeof SessionIdRouteWithChildren
  '/session/new': typeof SessionNewRoute
  '/session/$id/reflect': typeof SessionIdReflectRoute
  '/session/$id/summary': typeof SessionIdSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/appearance'
    | '/assistant'
    | '/dashboard'
    | '/history'
    | '/journal'
    | '/login'
    | '/reminders'
    | '/routine'
    | '/settings'
    | '/tools'
    | '/profile/setup'
    | '/session/$id'
    | '/session/new'
    | '/session/$id/reflect'
    | '/session/$id/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/appearance'
    | '/assistant'
    | '/dashboard'
    | '/history'
    | '/journal'
    | '/login'
    | '/reminders'
    | '/routine'
    | '/settings'
    | '/tools'
    | '/profile/setup'
    | '/session/$id'
    | '/session/new'
    | '/session/$id/reflect'
    | '/session/$id/summary'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/appearance'
    | '/assistant'
    | '/dashboard'
    | '/history'
    | '/journal'
    | '/login'
    | '/reminders'
    | '/routine'
    | '/settings'
    | '/tools'
    | '/profile/setup'
    | '/session/$id'
    | '/session/new'
    | '/session/$id/reflect'
    | '/session/$id/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AppearanceRoute: typeof AppearanceRoute
  AssistantRoute: typeof AssistantRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  JournalRoute: typeof JournalRoute
  LoginRoute: typeof LoginRoute
  RemindersRoute: typeof RemindersRoute
  RoutineRoute: typeof RoutineRoute
  SettingsRoute: typeof SettingsRoute
  ToolsRoute: typeof ToolsRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  SessionIdRoute: typeof SessionIdRouteWithChildren
  SessionNewRoute: typeof SessionNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routine': {
      id: '/routine'
      path: '/routine'
      fullPath: '/routine'
      preLoaderRoute: typeof RoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appearance': {
      id: '/appearance'
      path: '/appearance'
      fullPath: '/appearance'
      preLoaderRoute: typeof AppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/new': {
      id: '/session/new'
      path: '/session/new'
      fullPath: '/session/new'
      preLoaderRoute: typeof SessionNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/setup': {
      id: '/profile/setup'
      path: '/profile/setup'
      fullPath: '/profile/setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$id/summary': {
      id: '/session/$id/summary'
      path: '/summary'
      fullPath: '/session/$id/summary'
      preLoaderRoute: typeof SessionIdSummaryRouteImport
      parentRoute: typeof SessionIdRoute
    }
    '/session/$id/reflect': {
      id: '/session/$id/reflect'
      path: '/reflect'
      fullPath: '/session/$id/reflect'
      preLoaderRoute: typeof SessionIdReflectRouteImport
      parentRoute: typeof SessionIdRoute
    }
  }
}

interface SessionIdRouteChildren {
  SessionIdReflectRoute: typeof SessionIdReflectRoute
  SessionIdSummaryRoute: typeof SessionIdSummaryRoute
}

const SessionIdRouteChildren: SessionIdRouteChildren = {
  SessionIdReflectRoute: SessionIdReflectRoute,
  SessionIdSummaryRoute: SessionIdSummaryRoute,
}

const SessionIdRouteWithChildren = SessionIdRoute._addFileChildren(
  SessionIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AppearanceRoute: AppearanceRoute,
  AssistantRoute: AssistantRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  JournalRoute: JournalRoute,
  LoginRoute: LoginRoute,
  RemindersRoute: RemindersRoute,
  RoutineRoute: RoutineRoute,
  SettingsRoute: SettingsRoute,
  ToolsRoute: ToolsRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  SessionIdRoute: SessionIdRouteWithChildren,
  SessionNewRoute: SessionNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
